# Generated by Django 4.0.3 on 2022-09-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.IntegerField(default=50, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=55, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_type',
            field=models.CharField(choices=[('Newly Released', 'Newly Released'), ('Coming Soon', 'Coming Soon')], max_length=60, verbose_name='release_type'),
        ),
    ]
